#!/bin/sh
# Launch SliTaz default Web browser.
#
. /etc/slitaz/applications.conf

USER_CONFIG="$HOME/.config/slitaz/applications.conf"
[ -f  $USER_CONFIG ] && . $USER_CONFIG

EXEC="exec setsid $BROWSER"

if [ ! -z $XAUTHORITY ]; then
	EXECT="terminal -e $BROWSER";
	case $BROWSER in links) EXECT="$EXEC -g" ;; esac
else
	EXECT="$BROWSER";
fi

case $BROWSER in
	*links*|retawq|lynx)
		$EXECT $@ ;;
	w3m)	$EXECT -N $@ ;;
	qupzil*)$EXEC -pb -ow $@ ;;
	*)	$EXEC $@ ;;
esac

exit 0
