#!/bin/sh
# Launch SliTaz default Web browser.
#
. /etc/slitaz/applications.conf

USER_CONFIG="$HOME/.config/slitaz/applications.conf"
[ -f  $USER_CONFIG ] && . $USER_CONFIG

EXEC="exec setsid $BROWSER"

case $BROWSER in
	*links*|lynx)
		$EXEC $@ ;;
	w3m)	$EXEC -N $@ ;;
	*)	$EXEC $@ & ;;
esac

exit 0
