#!/bin/sh
# Launch SliTaz default Web browser.
#
. /etc/slitaz/applications.conf

USER_CONFIG="$HOME/.config/slitaz/applications.conf"
[ -f  $USER_CONFIG ] && . $USER_CONFIG

exec $BROWSER $@

exit 0
