#!/bin/sh
# Launch SliTaz default Text Editor.
#
. /etc/slitaz/applications.conf

USER_CONFIG="$HOME/.config/slitaz/applications.conf"
[ -f  $USER_CONFIG ] && . $USER_CONFIG

exec setsid $EDITOR $@

exit 0
