#!/bin/sh
SECTION=all
if [ -n "$2" ]; then
	SECTION=$1
	shift
fi
TOPIC=$1
wget -O - "http://man.he.net/?topic=$TOPIC&section=$SECTION" 2> /dev/null | \
awk 'BEGIN { s=0 } /<PRE>/ { s=1 } { if (s) print } /<\/PRE>/ { s=0 }' | \
sed -e 's/<[^>]*>//g' -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' | less
