#! /bin/sh
# 
# Gtkdialog box for the mount command. Part of SliTaz tools.
#
VERSION=20071105

# Check if user is root.
check_root()
{
	if test $(id -u) != 0 ; then
	   echo -e "\nYou must be root to run `basename $0` with this command."
	   echo -e "Please type 'su' and root password to become super-user.\n"
	   exit 0
	fi
}

# Mount and umount buttons with fiel for devive and mount point.
#
export MOUNT_DIALOG='
 <vbox>

  <text use-markup="true">
    <label>
"
<b>SliTaz - Mountbox</b>"
    </label>
  </text>
  <text wrap="true" width-chars="44" use-markup="true">
    <label>
"
Mount a device on a mount point. Device can be cdrom,
flash key, USB disk or local HD partitions. Please use the
<small>fdisk -l</small> to get a list of avalaible devices to mount
"
    </label>
  </text>
  
  <hbox>
    <text use-markup="true">
      <label>"<b>Device             : </b>"</label>
    </text>
    <entry>
      <default>/dev/sda1</default>
      <variable>DEVICE</variable>
    </entry>
  </hbox>
  
  <hbox>
    <text use-markup="true">
      <label>"<b>Mount point   : </b>"</label>
    </text>
    <entry>
      <default>/media/flash</default>
      <variable>MOUNT_POINT</variable>
    </entry>
  </hbox>

  <hbox>
    <button>
      <label>Mount</label>
      <input file icon="forward"></input>
      <action>echo -e "Mounting $DEVICE...\n"</action>
      <action>mkdir -p $MOUNT_POINT; mount $DEVICE $MOUNT_POINT; sleep 1</action>
      <action>echo; mount | grep $DEVICE; echo</action>
    </button>
    
    <button>
      <label>Umount</label>
      <input file icon="undo"></input>
      <action>echo -e "Unmounting $MOUNT_POINT...\n"</action>
      <action>umount $MOUNT_POINT; sleep 1</action>
      <action>echo; mount | grep $DEVICE; echo</action>
    </button>
    
    <button>
      <input file icon="exit"></input>
      <action type="exit">Exit</action>
    </button>
  </hbox>
  
 </vbox>
'

# Only root can mount.
check_root
gtkdialog --program=MOUNT_DIALOG

exit 0
