#!/bin/sh
#
# SliTaz Config - A tool with all SliTaz Ncurses configs in one place for
# text mode systems (server, ARM devices)
#
# Copyright (C) 2014 SliTaz ARM - BSD License
# Author: Christophe Lincoln <pankso@slitaz.org>
#
. /lib/libtaz.sh
check_root

title="{ SliTaz Config }"
about="/usr/share/doc/slitaz/post-install.txt"
tmpdir="/tmp/$(basename $0)"
tmp="$tmpdir/$$"
height="20"
width="72"

# Use a tmp directory
mkdir -p ${tmpdir}

#
# GUI Functions
#

# Coded for the ARM first boot settings
about_post_install() {
	dialog --cr-wrap \
		--title "{ Post Installation }" \
		--exit-label "Continue" \
		--textbox "$about" ${height} ${width}
}

# Set root passwd
root_passwd() {
	dialog --title "{ Root Password }" --colors \
		--inputbox "\nEnter new password for \Zb\Z1root" \
		12 ${width} 2>${tmp}
    passwd=$(cat $tmp)
    [ "$passwd" == "" ] && return 0
    echo "root:$passwd" | chpasswd --md5
}

# Add a new user
add_user() {
	title="{ Add User }"
	dialog --title "$title" --colors \
		--inputbox "\nEnter login name for the new \Zb\Z4user" 12 ${width} 2>${tmp}
	user=$(cat $tmp)
	[ "$user" == "" ] && return 0
	dialog --title "$title" --colors \
		--inputbox "\nEnter password for user \Zb\Z4${user}" 12 ${width} 2>${tmp}
	passwd=$(cat $tmp)
    [ "$passwd" == "" ] && return 0
    adduser -D -g "SliTaz User" -G users ${user}
    echo "$user:$passwd" | chpasswd --md5
    # User groups
    for group in audio cdrom video tty; do
		addgroup ${user} ${group}
	done
	# Slim default user on post-install
	if [ -f "/etc/slim.conf" ] && [ ! -f "/var/lib/slitaz/post-install" ]; then
		sed -i s"/default_user .*/default_user        $user/" /etc/slim.conf
	fi
}

set_date() {
	clear && newline
	echo -n "Old date:"; date
	rdate -s tick.greyware.com 2>/dev/null
	echo -n "New date:"; date
	sleep 4
}

# Main Dialog menu
main_box() {
	dialog \
		--clear --title "$title" \
		--ok-label "Exec" --cancel-label "Quit" \
		--menu "" ${height} ${width} 14 \
"keyboard"       "$(gettext 'System keyboard setting')" \
"locale"         "$(gettext 'System language setting')" \
"add-user"    "$(gettext 'Add a new user')" \
"root-passwd"    "$(gettext 'Change root password')" \
"set-date"       "$(gettext 'Set system date from the web')" \
"quit"           "$(gettext 'Exit from SliTaz Config')" 2>${tmp}
	
	# Handle options
	opt=${?}
	case "$opt" in
		1|255) rm -rf ${tmpdir} && exit 0 ;;
	esac
	
	# Handle actions
	action=$(cat $tmp)
	case "$action" in
		keyboard) tazkeymap ;;
		locale) tazlocale ;;
		add-user) add_user ;;
		root-passwd) root_passwd ;;
		set-date) set_date ;;
		quit) rm -rf ${tmpdir} && exit 0 ;;
	esac
}

#
# Handle commands
#

case "$1" in
	*_*) 
		# Execute functions 
		$@ ;;
	*)
		while true; do
			main_box
		done ;;
esac

# Clean exit
rm -rf ${tmpdir}
exit 0
