#!/bin/sh
#
# Gtkdialog to execute program as root from a WM menu.
# (c) SliTaz GNU/Linux 2008-2010 - GNU gpl.
#
VERSION=20100314

# Usage.
if [ -z "$1" ]; then
    echo "Slitaz subox version : $VERSION"
    echo -e "\nUsage : subox program\n"
    exit 0
fi

# Nothing to do if we are root
test $(id -u) = 0 && exec $1

# Include gettext helper script.
. /usr/bin/gettext.sh

# Export package name for gettext.
TEXTDOMAIN='subox'
export TEXTDOMAIN

# Keep command in an exported variable to be used by SU_DIALOG.
export SU_CMD=$1

# Main window and root password default entry set to 'root'.
export SU_DIALOG='
<window title="Subox" skip_taskbar_hint="true">
<vbox>

	<text use-markup="true">
		<label>"
<b>SliTaz - Subox</b>"
		</label>
	</text>
	<text wrap="true" width-chars="64">
		<label>"'`gettext "
Please enter root password (default root) to execute :"`'
'$@'
"
		</label>
	</text>
	
	<hbox>
		<text use-markup="true">
			<label>"'`gettext "<b>Administrator password :</b>"`'"</label>
		</text>
		<entry visibility="false">
			<variable>PASSWD</variable>
		</entry>
	</hbox>
	
	<hbox>
		<button ok>
			<action>echo $PASSWD | su -c "$SU_CMD" &</action>
			<action type="closewindow">SU_DIALOG</action>
		</button>
		<button cancel></button>
	</hbox>

</vbox>
</window>'

gtkdialog --center --program=SU_DIALOG

exit 0
