#!/bin/sh
#
# Tazkeymap - SliTaz GNU/Linux keymap config using loadkeys and dialog boxes.
# Configuration file is: /etc/keymap.conf
#
# Copyright (C) 2008-2012 SliTaz GNU/Linux - BSD License
#
# Author: Christophe Lincoln <pankso@slitaz.org>
#
: ${DIALOG=dialog}
. /lib/libtaz.sh
check_root

# Internationalization
. /usr/bin/gettext.sh
TEXTDOMAIN='slitaz-tools'
export TEXTDOMAIN

# List all keymaps.
list_keymaps() {
	cd /usr/share/kbd/keymaps/i386
	# We first need a list to sort and then use \n for Yad list.
	for i in $(find *rty *rtz dvorak -name *.map.gz)
	do
		keymap=$(basename $i)
		type=$(dirname $i)
		echo "${keymap%.map.gz} $type"
	done
}

# Load the selected kmap file from /usr/share/kbd/keymaps or Busybox kmaps.
load_keymap() {
	if [ -x /bin/loadkeys ]; then
		loadkeys $kmap
	else
		loadkmap < /usr/share/kmap/$kmap.kmap
	fi
}

# Config /etc/keymap.conf
system_config() {
	#gettext "Setting system keymap to:"; echo -n " $kmap"
	echo "$kmap" > /etc/keymap.conf
	#status
}

case "$1" in
	info)
		gettext "Config file   :"; echo " /etc/keymap.conf"
		gettext "Current keymap:"; echo " $(cat /etc/keymap.conf)" ;;
	list)
		list_keymaps | sort ;;
	"")
		# Default to text mode dialog.
		exec 3>&1
		value=$($DIALOG  --clear \
		--title " $(gettext "SliTaz keymap configuration") " \
		--menu "" 15 70 5 \
		$(list_keymaps | sort) \
		2>&1 1>&3)
		retval=$?
		exec 3>&-
		case $retval in
			0) continue ;;
			1|255) exit 0 ;;
		esac
		# If it's a reconfiguration give an info message.
		if [ -s /etc/keymap.conf ]; then
			msg=$(gettext "\
Please logout of your current session and login again to use new keyboard.")
			$DIALOG --clear --title " Information " --msgbox "$msg" 16 70
		fi
		kmap=$value
		system_config
		load_keymap ;;
	*)
		# Used to configure keymap from cmdline or scripts
		kmap=$1
		system_config
		load_keymap ;;
esac

exit 0
