#!/bin/sh
#
# Tazx - Ncurses startx script for SliTaz GNU/Linux using Dialog boxes.
# This tinyutils is part of slitaz-tools.
#
# 20080205 <pankso@slitaz.org> - GNU gpl v3.
#
: ${DIALOG=dialog}

# Variables.
XSERVER=Xvesa
DOC=/usr/share/doc/slitaz-tools/tazx.txt
MOUSE=/dev/input/mice,5
# WM can be specified on cmdline.
if [ -n "$1" ]; then
	WM=$1
else
	WM=jwm
fi

# Main dialog.
exec 3>&1
value=`$DIALOG --help-button \
	--clear --colors \
	--title " Configure X " \
	--menu \
"L'application 'tazx' permet de configurer votre session X.\n\
Gestionnaire de fenêtres : \Z2$WM\Zn" 16 70 5 \
"640x400x16" "TrueColor" \
"640x400x24" "TrueColor" \
"640x480x16" "TrueColor" \
"640x480x24" "TrueColor" \
"800x600x16" "TrueColor" \
"800x600x24" "TrueColor" \
"1024x768x16" "TrueColor" \
"1024x768x24" "TrueColor" \
"1280x800x16" "TrueColor" \
"1280x800x24" "TrueColor" \
"1280x1024x16" "TrueColor" \
"1280x1024x24" "TrueColor" \
"1600x1200x16" "TrueColor" \
"1600x1200x24" "TrueColor" \
"1920x1440x16" "TrueColor" \
"xterm" "800x600x16" \
"quit" "Quitter" \
2>&1 1>&3`
retval=$?
exec 3>&-

# Continue, exit or help...
case $retval in
	0)
		continue ;;
	1)
		echo "Cancel pressed..."
		exit 0 ;;
	2)
		$DIALOG --clear \
		--title " Aide - Help " --textbox "$DOC" 15 70
		exec tazx ;;
	255)
		if test -n "$value"; then
			continue
		else
			echo "ESC pressed..."
			exit 0
		fi ;;
esac

# Set selected value.
case $value in
	xterm)
		Xvesa -ac -shadow -screen 800x600x16 -br &
		exec xterm -cr orange -geometry 80x35+0-0 ;;
	*)
		SCREEN=$value ;;
esac

# Copy a JWM system config if any present in user home
if [ ! -f "$HOME/.jwmrc" ]; then
    cp /etc/jwm/system.jwmrc $HOME/.jwmrc
fi
# Change backgroud image if the 3/4 is not respected.
if echo $SCREEN | grep -q '1280x1024'; then
	sed -i s/'1024x768.png'/'1280x1024.png'/ $HOME/.jwmrc
fi
if echo $SCREEN | grep -q '1024x768'; then
	sed -i s/'1280x1024.png'/'1024x768.png'/ $HOME/.jwmrc
fi
# Tile Wallpaper for 1280x800.
if echo $SCREEN | grep -q '1280x800'; then
	sed -i s/'type="image"'/'type="tile"'/ $HOME/.jwmrc
fi

# e17 start with enlightenment_start.
if [ "$WM" == "e17" ]; then
	 WM=enlightenment_start
	 XSEVER_OPTS="dpms -terminate"
fi

# Creat ~/.xsession to keep the configuration selected.
#
cat > $HOME/.xsession << _EOT_
# ~/.xsession: Start X window session on your system.
#
$XSERVER -ac -shadow $XSEVER_OPTS -screen $SCREEN -mouse $MOUSE &
#mpg123 sound.wav &
#xterm -bg black -fg white -cr orange &
#xpad &
exec $WM
_EOT_

chmod 700 $HOME/.xsession

# Console messages.
echo "X server   : $XSERVER"
echo "Screen     : $SCREEN"
echo "Exec WM    : $WM"
echo ""

exit 0
