#!/bin/sh
#
# Libmountbox provides devices list in suitable format for GTK tree
# and various dialog boxes to mount, umount, etc.
#
# (C) 2009 - SliTaz GNU/Linux project.
#

# Short usage.
usage()
{
	echo -e "\nUsage: $0 command\n
Output commands:
  list-mounted      List all mounted devices in suitable GTK tree format.
  list-umounted     List all umounted in suitable GTK tree format.
  
GTKdialog boxes
  mounted-fs-infos  Display a mounted devices infos with actions.
  umounted-fs-infos  Display a umounted devices infos with actions.\n"
}

# Format df -h output for GTK tree.
mounted_fs_data()
{
	SIZE=`echo $RES | cut -d " " -f 2`
	USED=`echo $RES | cut -d " " -f 3`
	AVAILABLE=`echo $RES | cut -d " " -f 4`
	PCT=`echo $RES | cut -d " " -f 5`
	MOUNTED_ON=`echo $RES | cut -d " " -f 6`
}

# Update BLOCKS SIZE UUID TYPE LABEL variables
getdevinfo()
{
	local dev
	dev=${1#/dev/}
	BLOCKS=0
	if [ -f /sys/block/$dev/size ]; then
		BLOCKS=`cat /sys/block/$dev/size`
	elif [ -f /sys/block/*/$dev/size ]; then
		BLOCKS=`cat /sys/block/*/$dev/size`
	fi
	if [ $BLOCKS -gt 2097152 ]; then
		unit=G
		n=$(($BLOCKS * 10 / 2097152))
	elif [ $BLOCKS -gt 2048 ]; then
		unit=M
		n=$(($BLOCKS * 10 / 2048))
	else
		unit=K
		n=$(($BLOCKS * 5))
	fi
	SIZE=$(($n/10)).$(($n%10))$unit
	UUID=`blkid | grep ^/dev/$dev: | grep UUID= | sed 's/.*UUID=\"\([^\"]*\)\".*/\1/'`
	TYPE=`blkid | grep ^/dev/$dev: | grep TYPE= | sed 's/.*TYPE=\"\([^\"]*\)\".*/\1/'`
	LABEL=`blkid | grep ^/dev/$dev: | grep LABEL= | sed 's/.*LABEL=\"\([^\"]*\)\".*/\1/'`
}

case $1 in
	list-mounted)
		# List all fs found by: df -h
		#
		for dev in `df -h | grep ^/dev/ | cut -d " " -f 1`
		do
			RES=`df -h $dev | grep ^$dev`
			mounted_fs_data
			echo "$dev | $SIZE | $USED | $AVAILABLE | $PCT | $MOUNTED_ON"
		done ;;
	list-umounted)
		# List all umounted fs found by: fdisk -l
		#
		for dev in `fdisk -l | grep ^/dev | cut -d " " -f 1`
		do
			RES=`fdisk -l | grep $dev | sed s/*//g`
			START=`echo $RES | cut -d " " -f 2`
			END=`echo $RES | cut -d " " -f 3`
			BLOCKS=`echo $RES | cut -d " " -f 4`
			ID=`echo $RES | cut -d " " -f 5`
			SYSTEM=`echo $RES | cut -d " " -f 6-`
			# Bootable...
			if fdisk -l | grep $dev | grep -q "*"; then
				BOOT="yes"
			else
				BOOT="-"
			fi
			# Skip swap, extended, and mounted partitions.
			if echo $RES | grep -q "swap" || echo $RES | grep -q "Extended" ; then
				continue
			elif mount | grep -q "^$dev "; then
				continue
			else
				getdevinfo $dev
				echo "$dev | $SIZE | $SYSTEM | $TYPE | $LABEL | $BOOT | $START | $END | $BLOCKS | $ID | $UUID"
			fi
		done
		for dev in /dev/mapper/* ; do
			[ -b $dev ] || continue
			mount | grep -q "^$dev " && continue
			mdev=dm-$(ls -l $dev | awk '{ print $6 }')
			mount | grep -q "^/dev/$mdev " && continue
			getdevinfo /dev/$mdev
			echo "$dev | $SIZE | - | $TYPE | $LABEL | - | - | - | $BLOCKS | - | $UUID"
		done
		for dev in $(losetup | cut -d: -f1); do
			[ -b $dev ] || continue
			mount | grep -q "^$dev " && continue
			getdevinfo $dev
			echo "$dev | $SIZE | - | $TYPE | $LABEL | - | - | - | $BLOCKS | - | $UUID"
		done
		[ -e /dev/cdrom ] &&
		echo "/dev/cdrom | - | CD/DVD | iso9660 | - | - | - | - | - | - | -"
		for i in /sys/devices/platform/floppy.*/block:*; do 
			[ -e $i ] && echo "/dev/${i#*block:} | - | - | - | floppy | - | - | - | - | -"
		done
		;;
	mounted-fs-infos)
		# Mounted fs info and actions, rootfs or other fs.
		#
		if [ "$MOUNTED" == "/dev/root" ]; then
			export MOUNTED_DEVICE="
<window title=\"Device: rootfs\" icon-name=\"media-flash\">
<vbox>
	<text use-markup=\"true\" width-chars=\"56\">
		<label>\"
<b>/dev/root</b>
\"
		</label>
	</text>
	<text use-markup=\"true\" width-chars=\"56\">
		<input>df -h / | grep ^rootfs</input>
	</text>
	<hbox>
		<button>
			<label>Browse</label>
			<input file icon=\"folder-open\"></input>
			<action>pcmanfm / &</action>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>
	</hbox>
</vbox>
</window>"
		gtkdialog --center --program=MOUNTED_DEVICE
		else
			getdevinfo $MOUNTED
			RES=`df -h $MOUNTED | grep ^$MOUNTED`
			mounted_fs_data
			export MOUNTED_DEVICE="
<window title=\"Device: $MOUNTED\" icon-name=\"media-flash\">
<vbox>
	<text use-markup=\"true\" width-chars=\"56\">
		<label>\"
Device <b>$MOUNTED</b> is mounted on <b>$MOUNTED_ON</b>

Size: $SIZE
UUID: $UUID
Type: $TYPE
Label: $LABEL
\"
		</label>
	</text>
	<hbox>
		<button>
			<label>Browse</label>
			<input file icon=\"folder-open\"></input>
			<action>pcmanfm $MOUNTED_ON &</action>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>
		<button>
			<label>Umount</label>
			<input file icon=\"undo\"></input>
			<action>umount $MOUNTED_ON</action>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>
	</hbox>
</vbox>
</window>"
		gtkdialog --center --program=MOUNTED_DEVICE
		fi ;;
	umounted-fs-infos)
		# Mounted fs info and actions, rootfs or other fs.
		#
		case "$DEVICE" in
		/dev/mapper/*) mdev=/dev/dm-$(ls -l $DEVICE | awk '{ print $6 }');;
		*) mdev=$DEVICE;;
		esac
		getdevinfo $mdev
		export UMOUNTED_DEVICE="
<window title=\"Device: $DEVICE\" icon-name=\"media-flash\">
<vbox>
	<text use-markup=\"true\" width-chars=\"56\">
		<label>\"
Mount <b>$DEVICE</b> on <b>$MOUNT_POINT</b>

Size: $SIZE
UUID: $UUID
Type: $TYPE
Label: $LABEL
\"
		</label>
	</text>
	
	<hbox>
		<button>
			<label>Mount</label>
			<input file icon=\"edit-redo\"></input>
			<action>mkdir -p $MOUNT_POINT</action>
			<action>mount $DEVICE $MOUNT_POINT</action>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>"
while read type fsck args; do
	[ "$TYPE" == "$type" ] || continue
	which $fsck > /dev/null || continue
UMOUNTED_DEVICE="$UMOUNTED_DEVICE		
		<button>
			<label>$fsck check</label>
			<input file icon=\"drive-harddisk\"></input>
			<action>xterm -T \"$fsck $args $DEVICE\" \
				-geometry 80x12 \
				-e \"echo; $fsck $args $DEVICE; \
				echo -e '----\\nENTER to close Terminal'; \
				read i\" &</action>
			<action type=\"closewindow\">MOUNTED_DEVICE</action>
		</button>"
done <<EOT
ext3 e2fsck -p
ext2 e2fsck -p
vfat dosfsck -a
msdos dosfsck -a
xfs fsck.xfs -s
reiserfs reiserfsck --fix-fixable
jfs jfs_fsck -a
EOT
UMOUNTED_DEVICE="$UMOUNTED_DEVICE		
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">UMOUNTED_DEVICE</action>
		</button>
	</hbox>
</vbox>
</window>"
		gtkdialog --center --program=UMOUNTED_DEVICE ;;
	loopmgr)
		export LOOP_MANAGER="
<window title=\"Loop manager\" icon-name=\"media-flash\">
<vbox>
	<tree>
		<width>420</width><height>120</height>
		<variable>LOOP_DEV</variable>
		<label>Device|File|Size|Type|Label|Mounted on|Offset|UUID</label>"
		while read dev offset file; do
			DEV=$(echo $dev | cut -d: -f1)
			MOUNT=$(mount | grep ^$DEV | awk '{ print $3 }')
			getdevinfo $DEV
			LOOP_MANAGER="$LOOP_MANAGER
		<item>$DEV | $file | $SIZE | $TYPE | $LABEL | $MOUNT | $offset | $UUID</item>
		<action>/usr/lib/slitaz/libmountbox remove-loop</action>
		<action>/usr/lib/slitaz/libmountbox loopmgr &</action>
		<action type=\"closewindow\">LOOP_MANAGER</action>
"
		done <<EOT
$(losetup)
EOT
		LOOP_MANAGER="$LOOP_MANAGER
	</tree>
	<hbox>
		<text use-markup=\"true\">
			<label>\"<b>File</b>\"</label>
		</text>
		<entry accept=\"filename\">
			<variable>FILE</variable>
		</entry>
		<button>
			<input file icon=\"folder-open\"></input>
			<action type=\"fileselect\">FILE</action>
		</button>
	</hbox>
	<hbox>
		<text use-markup=\"true\" width=\"10\">
			<label>\"<b>Offset</b>\"</label>
		</text>
		<entry>
			<default>0</default>
			<variable>OFFSET</variable>
		</entry>
		<button>
			<label>Create</label>
			<input file icon=\"add\"></input>
			<action>/usr/lib/slitaz/libmountbox add-loop</action>
			<action>/usr/lib/slitaz/libmountbox loopmgr &</action>
			<action type=\"closewindow\">LOOP_MANAGER</action>
		</button>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">LOOP_MANAGER</action>
		</button>
	</hbox>
</vbox>
</window>"
		gtkdialog --center --program=LOOP_MANAGER ;;
	remove-loop)
		getdevinfo $LOOP_DEV
		export REMOVE_DEVICE="
<window title=\"Device: $LOOP_DEV\" icon-name=\"media-flash\">
<vbox>
	<text use-markup=\"true\" width-chars=\"56\">
		<label>\"
Disable <b>$LOOP_DEV</b> ?

Size: $SIZE
UUID: $UUID
Type: $TYPE
Label: $LABEL
\"
		</label>
	</text>
	<hbox>
		<button yes>
			<action>umount $LOOP_DEV</action>
			<action>losetup -d $LOOP_DEV</action>
			<action type=\"closewindow\">LOOP_MANAGER</action>
			<action>/usr/lib/slitaz/libmountbox loopmgr &</action>
			<action type=\"closewindow\">REMOVE_DEVICE</action>
		</button>
		<button no>
			<action type=\"closewindow\">REMOVE_DEVICE</action>
		</button>
	</hbox>
</vbox>
</window>"
		gtkdialog --center --program=REMOVE_DEVICE ;;
	add-loop)
		losetup -o $OFFSET $(losetup -f) $FILE
		;;
	*)
		usage ;;
esac

exit 0
