# SliTaz desktopbox messages.

CHARS_SIZE="64"
NEW_FOLDER_LABEL="Create a new folder on the desktop:"
FOLDER_ENTRY_MSG="dirname"
NEW_FILE_LABEL="Create a new file on the desktop:"
FILE_ENTRY_MSG="filename"
ADD_ICON_LABEL="Add some desktop icons"
DESKTOP_DIALOG_TAZUSB="Save filesystem using compression"
DESKTOP_DIALOG_LABEL="Session logout, system shutdown or reboot"
DESKTOP_LOGOUT_BUTTON="Logout X session"
DESKTOP_SHUTDOWN_BUTTON="Shutdown computer"
DESKTOP_REBOOT_BUTTON="Reboot system"
