#!/bin/sh
#
# SliTaz tiny GUI boxes for the desktop (su, logout, etc) and as usual
# please KISS
#
# Note: $(gettext "text") doesn't work inside Yad so use `gettext \"text\"`
#
# Copyright (C) 2011 SliTaz GNU/linux - GNU gpl v3
#    - Christophe Lincoln <pankso@slitaz.org>
#

# Download dir (may be in a config file)
DOWNLOADS=$HOME/Downloads

# Internationalization
. /usr/bin/gettext.sh
TEXTDOMAIN='tazbox'
export TEXTDOMAIN

# Icons for most windows
icon=/usr/share/pixmaps/slitaz-menu.png

#
# Functions
#

usage() {
	cat << EOT

$(gettext "Usage:") $(basename $0) [command]

$(gettext "Commands:")
  usage      $(gettext "Display this short help usage")
  logout     $(gettext "Desktop logout box with actions")
  out        $(gettext "Pipe a command output into a GTK window")
  out-dl     $(gettext "Pipe Wget output into a GTK window")

EOT
}

cancel_dl() {
	if [ "$?" == 1 ]; then
		echo "CANCEL"
		rm -f $DOWNLOADS/$(basename $url)
	fi
}

# Outup a command in a GTK window
output_command() {	
	yad --text-info --title="TazBox Output" --window-icon=$icon \
		--geometry="560x210+0-24" --fore="#ffffff" --back="#000000"
}

# Logout GUI function
logout_main() {
	text=$(gettext "SliTaz Logout. Please choose an action:")
	yad --entry --title="SliTaz Logout" --window-icon=$icon \
		--width=440 --height=150 --text="$text" \
		--image="slitaz-menu" --image-on-top \
		--center --on-top  --entry-text \
			"`gettext \"Close X session\"` : exit" \
			"`gettext \"Reboot system\"` : reboot" \
			"`gettext \"Shutdown system\"` : halt"
}

#
# Commands
#
case "$1" in
	su)
		# Execute a command as root
		echo "TODO" ;;
	logout)
		# Lougout window with actions
		main=`logout_main`
		# Deal with --button values
		case $? in
			1) exit 0 ;;
			*) continue ;;
		esac
		# Deal with $main values
		case "$main" in
			*exit) openbox --exit || jwm -exit ;;
			*reboot) reboot ;;
			*halt) poweroff ;;
		esac ;;
	out)
		# Pipe a command into a GTK window
		output_command ;;
	dl-out)
		# A tiny GTK window for Busybox wget output
		url=$2
		busybox wget -c -P $DOWNLOADS $url 2>&1 | output_command
		cancel_dl ;;
	*)
		usage ;;
esac

exit 0
